on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag for publishing chart
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}

      - name: Install Helm
        uses: Azure/setup-helm@v4
        id: install

      - name: Lint Helm chart
        run: helm lint helm/joseph-test

      - name: Log in to GitHub Container Registry
        if: github.ref_type == 'tag'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/${{ github.repository }} --username ${{ github.repository_owner }} --password-stdin

      - name: Package Helm chart to container registry
        if: github.ref_type == 'tag'
        run: |
          helm dependencies update helm/joseph-test
          helm package helm/joseph-test --version ${{ steps.meta.outputs.version }} --app-version ${{ steps.meta.outputs.version }} -d /tmp/
          helm push /tmp/joseph-test-${{ steps.meta.outputs.version }}.tgz oci://ghcr.io/${{ github.repository }}/charts
