on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create tags for publishing image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=tag
            type=raw,value=latest

      - name: Install Helm
        uses: Azure/setup-helm@v4
        id: install

      - name: Lint Helm chart
        run: helm lint joseph-test

      - name: Log in to GitHub Container Registry
        if: github.ref_type == 'tag'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/${{ github.repository }} --username ${{ github.repository_owner }} --password-stdin

      - name: package chart and push it
        if: github.ref_type == 'tag'
        run: |
          helm dependencies update helm/test_joseph
          helm package helm/test_joseph --version ${{ steps.meta.outputs.version }} --app-version ${{ steps.meta.outputs.version }} -d /tmp/
          helm push /tmp/test_joseph-${{ steps.meta.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
